from __future__ import annotations

import argparse
import subprocess
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

FORBIDDEN_DIR_NAMES = {
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    "node_modules",
    "dist",
    "coverage",
    "htmlcov",
}
FORBIDDEN_DIR_SUFFIXES = (".egg-info", ".dist-info")
SOURCE_SCAN_DIRS = ("backend", "frontend", "scripts", "docs")
SOURCE_SCAN_ROOT_FILES = (
    ".env.example",
    ".gitignore",
    ".python-version",
    "API_CONTRACT.md",
    "ARCHITECTURE.md",
    "CHANGELOG.md",
    "DELIVERY_CHECKLIST.md",
    "PROJECT_STRUCTURE.md",
    "QUICK_START.md",
    "README.md",
    "RELEASE_CHECKLIST.md",
    "SECURITY_MODEL.md",
    "SETUP_VUE.md",
    "TESTING.md",
    "VERSION",
    "pyproject.toml",
    "pytest.ini",
)
LOCAL_ONLY_SKIP_DIRS = {
    ".git",
    ".mypy_cache",
    ".openapi-runtime",
    ".pytest-chroma",
    ".pytest-tmp",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    ".venv311",
    ".venv311_clean",
    "autotest_uploads",
    "chroma_db",
    "venv",
    "env",
    "openapi_runtime",
    "pytest_run",
    "pytest_runtime",
    "uploads",
}


def _is_forbidden_path(path: str) -> bool:
    parts = [part for part in Path(path).parts if part not in ("", ".")]
    return any(
        part in FORBIDDEN_DIR_NAMES
        or part.endswith(FORBIDDEN_DIR_SUFFIXES)
        or part == "frontend/dist"
        for part in parts
    )


def _git_tracked_paths(root: Path) -> list[str] | None:
    if not (root / ".git").exists():
        return None
    result = subprocess.run(
        ["git", "ls-files"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        return None
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def _should_prune_local_dir(rel_parts: tuple[str, ...]) -> bool:
    if not rel_parts:
        return False
    if any(part in LOCAL_ONLY_SKIP_DIRS for part in rel_parts):
        return True
    # These are intentionally generated by local verification commands such as
    # npm ci and npm run build; release/source zips verify they are excluded.
    return any(part in {"node_modules", "dist", "coverage", "htmlcov"} for part in rel_parts)


def _source_walk_paths(root: Path) -> list[str]:
    paths: list[str] = []
    for dirname in SOURCE_SCAN_DIRS:
        start = root / dirname
        if not start.exists():
            continue
        for candidate in start.rglob("*"):
            rel_parts = candidate.relative_to(root).parts
            if _should_prune_local_dir(rel_parts):
                continue
            rel = candidate.relative_to(root).as_posix()
            paths.append(rel)
    for filename in SOURCE_SCAN_ROOT_FILES:
        if (root / filename).exists():
            paths.append(filename)
    return paths


def find_forbidden_source_paths(root: Path = ROOT) -> list[str]:
    tracked = _git_tracked_paths(root)
    paths = tracked if tracked is not None else _source_walk_paths(root)

    bad = sorted({path for path in paths if _is_forbidden_path(path)})

    # Git ignores generated packaging/cache directories, so also scan package-included
    # source roots while pruning local dependency/build outputs.
    for path in _source_walk_paths(root):
        if _is_forbidden_path(path):
            bad.append(path)
    return sorted(set(bad))


def find_forbidden_zip_paths(zip_path: Path) -> list[str]:
    with zipfile.ZipFile(zip_path) as archive:
        names = archive.namelist()
    return sorted({name for name in names if _is_forbidden_path(name)})


def check_source_tree(root: Path = ROOT) -> None:
    bad = find_forbidden_source_paths(root)
    if bad:
        raise SystemExit(
            "Forbidden generated artifacts in source tree:\n"
            + "\n".join(bad[:200])
        )
    print("OK: source tree artifact check passed")


def check_zip(zip_path: Path) -> None:
    bad = find_forbidden_zip_paths(zip_path)
    if bad:
        raise SystemExit(
            "Forbidden paths in zip (generated artifacts):\n" + "\n".join(bad[:200])
        )
    print(f"OK: zip artifact check passed for {zip_path}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Check source trees and release/source zips for generated artifacts."
    )
    parser.add_argument("--root", default=str(ROOT))
    parser.add_argument("--zip", dest="zip_path", default="")
    args = parser.parse_args()

    if args.zip_path:
        check_zip(Path(args.zip_path))
    else:
        check_source_tree(Path(args.root))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
